### ISSUE TITLE
sim method definitions

### ISSUE THREAD

**Issue by tshort** [tshort/Sims.jl#15]
The current `sim` API is as little messy. To straighten up, I propose the following:

```julia
sim(m::Model, tstop::Float64=1.0, Nsteps::Int=500, reltol::Float64=1e-4, abstol::Float64=1e-4)
sim(m::Model; tstop::Float64=1.0, Nsteps::Int=500, reltol::Float64=1e-4, abstol::Float64=1e-4)
sim(s::Sim, tstop::Float64=1.0, Nsteps::Int=500, reltol::Float64=1e-4, abstol::Float64=1e-4)
sim(s::Sim; tstop::Float64=1.0, Nsteps::Int=500, reltol::Float64=1e-4, abstol::Float64=1e-4)
sim(ss::SimState, tstop::Float64=1.0, Nsteps::Int=500, reltol::Float64=1e-4, abstol::Float64=1e-4)
sim(ss::SimState; tstop::Float64=1.0, Nsteps::Int=500, reltol::Float64=1e-4, abstol::Float64=1e-4)
```

Everything after the first argument is either a positional with default or a keyword argument.

Looking again at having `Sim` and `SimState`, I'm again inclined to want to flatten them into one structure. Thoughts, @iraikov? Then, we can add more options to `sim` or add other helpers to adjust the state of a combined Sim/SimState.

Going further astray...

It'd be nice to be able to pass Parameter changes into `sim`. For an API, we could pass a Dict or new Parameters object. We also might be able to directly pass changes to the SimState object, like:

```julia
sim( ss( paramX = 27.0, paramN = 12 ), tstop = 5.0 )
``` 
The new :call overloading capability in Julia 0.4dev allows that.

**Comment by iraikov** [comment]
I like the direction of using keywords for most arguments. I also agree that there is a need for passing Parameter changes and for having distributions for parameters.
One of the reasons for separating Sim and SimState was to save some memory in the case when creating multiple instances of the same set of equations. What is a good way to measure the memory use in both cases?

**Comment by tshort** [comment]
I haven't really tried to track down memory issues before. There was a recent thread on that:

https://groups.google.com/forum/#!topic/julia-users/MpCaRxrmR1s
