### ISSUE TITLE
Unknown method definitions

### ISSUE THREAD

**Issue by tshort** [tshort/Sims.jl#16]
More housekeeping. I propose the following to clean up the spaghetti of Unknown definitions:

```julia
type Unknown{T<:UnknownCategory} <: UnknownVariable
    sym::Symbol
    value         # holds initial values (and type info)
    label::String
    fixed::Bool
    save_history::Bool
    Unknown(;value = 0.0, label::String = "", fixed::Bool = false, save_history::Bool = false) =
        new(gensym(), value, label, fixed, save_history)
    Unknown(value = 0.0, label::String = "", fixed::Bool = false, save_history::Bool = false) =
        new(gensym(), value, label, fixed, save_history)
    Unknown(label::String = "", value = 0.0, fixed::Bool = false, save_history::Bool = false) =
        new(gensym(), value, label, fixed, save_history)
end
Unknown(value = 0.0, label::String = "", fixed::Bool = false, save_history::Bool = true) =
    Unknown{DefaultUnknown}(value, label, fixed, save_history)
Unknown(label::String = "", value = 0.0, fixed::Bool = false, save_history::Bool = true) =
    Unknown{DefaultUnknown}(value, label, fixed, save_history)
Unknown(;value = 0.0, label::String = "", fixed::Bool = false, save_history::Bool = true) =
    Unknown{DefaultUnknown}(value, label, fixed, save_history)
```

This will allow the following common uses:

```julia
Unknown("my label")
Unknown(3.14)
Voltage(120.0)
Voltage(120.0)
Voltage(value = 120.0)
```

Adding units will take more thought, but those can either slide into the list of arguments (probably 3rd) or could possibly be added or associated with the `T` type parameter.

**Comment by iraikov** [comment]
Hello Tom,

This does look a lot cleaner. I implemented it in my repository (branch new-unknown) but I had to add a clause to Unknown that takes a symbol as an argument, in order to allow the definition of MTime. Furthermore, this seems to break all uses of the unknown macro. In particular, the initial_conditions example does not work with the updated definition of Unknown.

**Comment by tshort** [comment]
Thanks. I hadn't actually tried running it with the proposed change. I'll
see if I can fix the macro. Also, I have a lot of changes coming on the
documentation branch, so this might test me git skills to merge them:)
