### ISSUE TITLE
delay() is broken

### ISSUE THREAD

**Issue by tshort** [tshort/Sims.jl#36]
@iraikov, this is one of the things you changed. Can you please refresh my memory on why you pulled history out of Unknowns? `delay` is currently broken. Do you know if it's hard to fix with your new SimStateHistory?

We should include an example with `delay`, so that testing catches this.

**Comment by iraikov** [comment]
Hi Tom,

    I pulled the history out of unknowns, because having multiple copies of
the same Sim with different parameters results in clobbering state history
in different simulation runs. Let me take a look and try to fix delay.

   Ivan

**Comment by iraikov** [comment]
I have updated the resid and event_at interface so that they receive history as an argument, which then can be used by the mexpr generated by delay. You can take a look at it in my fork. I will add a delay example tomorrow and do some serious testing.

**Comment by iraikov** [comment]
I have just submitted a pull request to fix this issue, however it appears that the dassl flag[16] needs to be set to zero in order for the delay equation example to work. Let me know how you want to proceed with this.

**Comment by tshort** [comment]
Fixed by #38.
