### ISSUE TITLE
Simulation timestep and output sampling timestep

### ISSUE THREAD

**Issue by iraikov** [tshort/Sims.jl#46]
A few of the neural examples need to have their output sampled at a relatively small timestep, 0.001 or so, which currently requires a simulation timestep of this size. However, this results in wasteful calls to IDASolve: IDA provides access to its internal interpolation tables via GetDky and that means the simulation timestep can be relatively large, while interpolated  dense output can be obtained via calls to GetDky. Is there similar functionality in DASSL? If so, perhaps we can introduce an additional output sampling timestep in the solver parameters.

**Comment by tshort** [comment]
No idea here...

**Comment by tshort** [comment]
In reading the dassl code, it looks like INFO[4] does what you're looking for.

**Comment by iraikov** [comment]
Unfortunately, one has to dig pretty deep into the DASSL internals to get that to work, and in Sundials, the range of interpolated outputs is limited by the internal timestep, which makes it very difficult to get output at equal intervals, so I am closing this.
