### ISSUE TITLE
value(m::MExpr) is broken when m has an equation that uses delay

### ISSUE THREAD

**Issue by tshort** [tshort/Sims.jl#49]
I've got a [speed/memory improvement](https://github.com/tshort/Sims.jl/compare/resid-less-copying?expand=1) for the residual calculation that depends on `value` working for equations and initial equations. It mostly works well. `value(e::MExpr)` is  also a nice feature to have in general:

```julia
julia> e = elaborate(Sims.Examples.Basics.VanderpolWithEvents());

julia> e.equations[1]
:(<<der(x),0.0>> - ((<<discrete,1.0>> * (1 - <<y,1.0>>^2)) * <<x,0.0>> - <<y,1.0 >>))

julia> value(e.equations[1])
1.0
```

`value` is broken when an equation has `delay`. Here is the DDE example with a delay:

```julia
julia> e = elaborate(Sims.Examples.Basics.DDE());

julia> e.equations[1]
:(<<der(x),-1.0>> - (-<<x,1.0>> + 1 / (1 + exp(-(((4 * <<x,1.0>> - 4.8 * Sims._interp(<<x,1.0>>,history.t,history.x,t[1] - 3.0)) + -0.8))))))

julia> value(e.equations[1])
ERROR: history not defined
 in value at c:\portableapps\home\.julia\v0.3\Sims\src\main.jl:555
 in map at base.jl:189

```

I'm still think that history is best stored with unknowns. Then, it'd be easy to make `value` work right with `delay`.

@iraikov, I'm curious on your feedback here. What is the use case you have that needs history stored separately from variables?

**Comment by iraikov** [comment]
I think the separation of SimStateHistory was a side effect of my temporary attempt to allow the creation of multiple Sundials instances from a single SimState. The (somewhat hypothetical) use case is to simulate networks of oscillators that are copies of the same set of equations but with different parameters. But you are very welcome to put the history back in the unknowns; I have not yet done much with network models, so I am not going to insist on separating the history.
