### ISSUE TITLE
Problems with multiple events

### ISSUE THREAD

**Issue by iraikov** [tshort/Sims.jl#55]
It appears that after recent changes, reinit in events can no longer change the values of Discretes. E.g. the following does not change the value of I_stim:

```julia
I_stim = Discrete (0.0)

@equations begin
der(v) = I_stim + .... 

# Set the value of I_stim at t = 250
       Event(MTime - 250.0,     
              Equation[
                  reinit(I_stim, 1.0)
              ],
              Equation[])

end
```

**Comment by tshort** [comment]
@iraikov, I can't reproduce. With Julia v0.3.5 and the latest Sims, `Sims.Examples.Basics.VanderpolWithEvents()` works fine as does the following:

```julia
using Sims
function m()
    a = Unknown("a")
    d = Discrete()
    Equation[
        a - d
        Event(MTime - 0.1, reinit(d, 2.0))     
    ]
end
s = create_simstate(m())
y = sim(s);
using PyPlot
plot(y)
```
Could you please let me know what Julia version you're using and the complete example you used?

**Comment by iraikov** [comment]
Thanks for looking at this so quickly.
I am also using Julia 0.3.5 and Sims from the master branch. It seems that the problem is not with reinit, but with having more than one event. The example is neural/cgc.jl which has one event at MTime-250.0 and one event at MTime-800.0. It seems that only the last event in the model gets detected. Can you try having several events and see if it works for you?

**Comment by tshort** [comment]
Interesting. That's reproducible for me.

**Comment by tshort** [comment]
Hopefully fixed. Silly mistake...

**Comment by iraikov** [comment]
Thanks a lot for the quick fix!

  -Ivan
