### ISSUE TITLE
New syntax to replace {}

### ISSUE THREAD

**Issue by tshort** [tshort/Sims.jl#6]
Because curly brackets are going away (https://github.com/JuliaLang/julia/pull/8578), we need something else. Two options I can think of are:

## Option 1

```julia
Equations[
    der(x, -1.0) - ((1 - y^2) * x - y)
    der(y) - x
]
```
or
```julia
Model[
    der(x, -1.0) - ((1 - y^2) * x - y)
    der(y) - x
]
```
This is the easiest change. We'd just need to set `Equations = Any`.

## Option 2

```julia
@model begin
    der(x, -1.0) = (1 - y^2) * x - y
    der(y) = x
end
```
This has the advantage that we write the macro to allow `=` in model equations. We could support either or both of these.

Here are options I don't think will work:
    - `@model { ... }` -- Curly brackets are depreciated in the parser, so macros don't help us avoid that.
    - `[ ... ]` -- uses `vcat`

**Comment by iraikov** [comment]
Actually, I just realized I forgot to convert the examples to the new
syntax. Maybe we should wait to close this ticket until this is done.

**Comment by tshort** [comment]
Okay, reopening...

**Comment by tshort** [comment]
I'll go through the standard library and convert to one of these. Any preference?

**Comment by iraikov** [comment]
I was just looking at the vanderpol and vanderpol_with_events examples, and
discovered that neither @equations not Equation works with examples that
have events in them. This is apart from the issue that Equations does not
work with one-liners.

When I replace {} with @equations begin .. end in vanderpol_with_events,
leaving the Event definitions as they are,
I get the error, "ERROR: `getindex` has no method matching
getindex(::Function, ::Nothing, ::MExpr, ::Nothing, ::MExpr, ::Nothing,
::MExpr, ::Nothing, ::Event)"

Anyway, to answer your question, I prefer @equations for systems with
multiple equations, and Equation[] for single equations and things like
Event(..,{},{}).

**Comment by tshort** [comment]
I'm not surprised on the macro, but I am on the Equation[]. Hmm...

**Comment by iraikov** [comment]
I stand corrected, Equations[] works, I had just forgotten the commas... I
must admit I do not understand Julia macros enough to know how to debug
@equations.

**Comment by tshort** [comment]
I'll take a look tomorrow. Also, you shouldn't need commas...

**Comment by iraikov** [comment]
If you can also look at Event, it seems to rely on the {} syntax so it
would need to be rewritten to use Equations[] (I think).

**Comment by tshort** [comment]
I've gotten the examples converted. I'll work on stdlib now.

**Comment by tshort** [comment]
@iraikov, this should be done, but please check your examples. There's a chance that I goofed parens accidentally.

**Comment by iraikov** [comment]
Hi Tom,

   All of the neural examples work, except for the only one that has
structural events:

https://github.com/tshort/Sims.jl/blob/master/examples/neural/iafrefr.jl

It seems that the trefr constant, computed on line 57 is somehow not
visible in the call to the Refractory function.
Any idea what is going on? Thanks,

    -Ivan

**Comment by tshort** [comment]
I don't think that should have worked. `trefr` shouldn't be visible. I pushed a version that may get around it. This again didn't work with `@equations` in one spot. I'll try to dig deeper.

**Comment by iraikov** [comment]
Thanks for looking at this. Of course, I would be happy with different
syntax, but the important thing is to be able to pass arguments to the
StructuralEvent transition function.

**Comment by tshort** [comment]
I think I fixed the `trefr` issue. It should have been obvious to me what was going on...

**Comment by iraikov** [comment]
Works like a charm, thanks a lot!
