### ISSUE TITLE
Added Sims.jl to Docile projects

### ISSUE THREAD

**Issue by peter1000** [tshort/Sims.jl#61]
hi,

would you mind if I add Sims.jl to the 
[Projects using Docile / Lexicon](https://github.com/MichaelHatherly/Docile.jl#projects-using-docile--lexicon)

**Comment by tshort** [comment]
Feel free!

**Comment by peter1000** [comment]
thanks

**Comment by tshort** [comment]
Here are some other packages that use Mkdocs for documentation. Most of these use Docile/Lexicon. DataFrames documentation is still a work in progress.

https://www.google.com/search?q=mkdocs.yml+jl+site:github.com&ie=utf-8&oe=utf-8

**Comment by peter1000** [comment]
Thanks
