### ISSUE TITLE
Move MExpr type and operations to a separate small package?

### ISSUE THREAD

**Issue by tkelman** [tshort/Sims.jl#64]
What would folks think about this? I have some projects where I'd be looking into doing wrappers for nonlinear control around JuMP, which would likely involve some macro code and an almost-exact copy of the MExpr type and methods on it. Not urgent at the moment, but planning a bit ahead here as other members of my lab are starting to use JuMP and we're thinking about things that could make it more convenient for us. Would it be inconvenient for Sims to have that code moved out into its own package?

**Comment by tshort** [comment]
I'm good with this idea, @tkelman. Is there an umbrella organization that could house the mexpr package?

**Comment by tkelman** [comment]
Maybe JuliaDiff, but it's more a generic little metaprogramming / operator-overloading helper type so isn't strictly limited to that purpose.

**Comment by tkelman** [comment]
I may have to work on this a little sooner than I thought I would. What we be the easiest way to go about this, have me do all the work on a personal repo (something like `ExprOverloads.jl` maybe?) then transfer ownership to you and do the PR to make Sims use it once it's registered and working?

The only thing I'm a little bit concerned about is that you have an abstract `ModelType` here that `MExpr` is a subtype of. I don't think it makes sense to move that abstract type definition to a separate package, and I don't know whether it's possible to make a concrete type from a separate package be a subtype of an abstract type, without a circular dependency.

Maybe it would be easier for me to just locally copy-paste this code for now, as ugly as that is from a version-control standpoint.

**Comment by tshort** [comment]
@tkelman, as far as the subtype issue, that can probably be handled with unions or better yet, a Tim Holy-style trait. Don't feel you have to do the Sims side of it.

I'm good with your plan to start by creating your repo. As far as transfering, it'd be best to transfer to a community site where we both have access.

**Comment by jalving** [comment]
It's now over a year later, but was there any outcome on this?  I'm also interested in using generic model expressions to interact with JuMP, and MExpr might just fit the bill.

**Comment by tkelman** [comment]
Never got around to it. JuMP has implemented their own mechanisms in the meantime.

**Comment by jalving** [comment]
Thanks.  I was mostly interested if equation expressions would be generalized.  JuMP's facilities will be more than capable right now.
