### ISSUE TITLE
Separate DASKR wrapper to a different package?

### ISSUE THREAD

**Issue by ChrisRackauckas** [tshort/Sims.jl#69]
It would be nice to have a DASKR.jl just for the DASKR wrapper, so that way the DAE solver could be used directly. How hard would that be given the current state of the code?

**Comment by tshort** [comment]
@ChrisRackauckas, it'd be easy for just the wrapper. (BTW, great job with the whole JuliaDiffEq org/community!) DASKR is only one FORTRAN routine to wrap. If you're interested in any of the following, I'll need some help, though:

* BinDeps--I don't have anything fancy for installation right now. It's really up to the user to get FORTRAN installed. I've looked at BinDeps before and never really figured it out.

* Common API--I'm pretty new to this.

* Tests--Some of your existing work would help here.

Anyway, if you think it's worth a shot, I could draft a package.

**Comment by ChrisRackauckas** [comment]
>BinDeps--I don't have anything fancy for installation right now. It's really up to the user to get FORTRAN installed. I've looked at BinDeps before and never really figured it out.

I think ODEInterface.jl's style of "if you have a FORTRAN compiler, it'll work" is fine.

>Common API--I'm pretty new to this.
Tests--Some of your existing work would help here.

Sure thing. If you put a draft together that shows how to call the solver, I can pretty easily get it to the API. Note I probably won't get around to it for like a week (I shouldn't be coding today... should be a paper writing day...).

**Comment by tshort** [comment]
@ChrisRackauckas, I put together a quick-n-dirty repo here:

https://github.com/tshort/DASKR.jl

Notes:

- It has a crude/partial common API interface, but I didn't know what I was doing. I mainly copied the Sundials function.
- The common API doesn't support events. I think callbacks may still be a work in progress. 
- There are a few helpers that help set up callbacks for the solver (residual, jacobian, and event handling). These use the `ipar` field to pass along size of the system along with other info. A more general way to pass data would be better. 
- Nothing is exported.

For the common API to be usable in Sims, it'll need to support events. Also, it'll be challenging for the common API to handle things like a banded jacobian (not that we handle that now, but maybe someday).

**Comment by ChrisRackauckas** [comment]
>It has a crude/partial common API interface, but I didn't know what I was doing. I mainly copied the Sundials function.

I'll submit some PRs.

>The common API doesn't support events. I think callbacks may still be a work in progress.

Yes. That is a big issue right now that we don't quite know how to solve. Maybe separating callback and event interfaces would do better than the current proposal of trying to have a common callback interface? The problem is that different packages need/can have very different code injected in via callbacks, so that's hard to standardize.

https://github.com/JuliaDiffEq/Roadmap/issues/10

>Also, it'll be challenging for the common API to handle things like a banded jacobian (not that we handle that now, but maybe someday).

Is passing this information as part of the algorithm type not possible (like how Sundials does it)? I see you have a flag for `:dense` which isn't used, so I guess the problem is more subtle (probably to do with the interop?).
