### ISSUE TITLE
Broken tests on Julia 0.4 and 0.5

### ISSUE THREAD

**Issue by tshort** [tshort/Sims.jl#71]
Although the current master passes tests, some models and examples are still broken. They run, but the results are wrong. The problems (I think) are in the event system and may be due to changes in React.

**Comment by iraikov** [comment]
I can help with that if you point me to the specific examples that are
broken.

**Comment by tshort** [comment]
I think it's anything with an `Event`. `StructuralEvents` seem to work. I think the events are getting triggered in Sundials or DASSL, but the changes are not propagating. Unfortunately, I don't remember that part of the code well.

A lot of the electrical models fail because they have a `StepVoltage`. `Sims.Examples.Basics.VanderpolWithEvents` is another that doesn't work. `reinit` isn't working.

This also points out that we need to have a better way of testing the results of simulations.

**Comment by iraikov** [comment]
Ok, I will take a look in a couple of hours. I have one or two neural examples with structural events, and anyway I need to check the grid stuff. I wholeheartedly agree about having  a better way for testing, but how to test models with no analytical solution? Would the ODE.jl developers have some ideas?

**Comment by iraikov** [comment]
I meant to say I have one or two neural examples with events.

**Comment by iraikov** [comment]
It looks like ev_pos_thunk and ev_neg_thunk are created but never used, perhaps this is why event handlers are never invoked.

**Comment by iraikov** [comment]
Correction, only ev_pos_thunk is never used. After adding ev_pos_thunk to the call on line 256 in simcreation,jl, the event handlers do get invoked.

**Comment by tshort** [comment]
That's a bug, Ivan. It doesn't fix the tests for me, though. (I may need to start fresh from the repo, though.)

**Comment by iraikov** [comment]
There could be other bugs, of course; but for example in  the VanderpolWithEvents model, it looks like the mu_u variable is getting the updated value of mu after each reinit. Can you check and tell me what should be the correct behavior for this model after applying the fix above? It probably is a good idea to start afresh, I was actually getting segfaults when I first tried your compiled closure commit, so I had to recompile everything.

**Comment by tshort** [comment]
I tried with a fresh repo, and the Event tests still don't work for me after fixing the bug you found, @iraikov. It must be something deeper. I can't remember what the exact behavior should be for VanderpolWithEvents, but the last three variables shouldn't stay constant.

**Comment by iraikov** [comment]
Hm, this might some peculiarity with discrete variables; when I wrote that
I see the mu variable changing, I had put a println  that prints the
updated state in the positive crossing handler. I just removed the println,
and now indeed mu does not change. Very odd, and I will investigate further.

**Comment by tshort** [comment]
It looks like Reactive changed how it works. `push!(x::Signal)` doesn't propagate immediately. It just "queues an update". Here's an example where the value isn't updated immediately.

```julia
julia> using Reactive

julia> x = Signal(0.0)
Signal{Float64}(0.0, nactions=0)

julia> push!(x, 9); println(x.value); println(x.value)
0.0
9.0 
```
The updated value didn't appear until the second `println`. I think this is what's preventing updates of `Discrete` variables in Sims. I also think I have a kludgy fix by appending `Reactive.push!()` with `Reactive.run_till_now()`. I'll try it in a PR.

**Comment by iraikov** [comment]
There is also something called send_value! that seems to perform all the
actions queued in a Reactive variable.

**Comment by tshort** [comment]
That sounds useful, but I'm not sure what the timestep argument means. Anyway, I dislike all of this because it means we have to use the internals of Reactive rather than the public API.

**Comment by iraikov** [comment]
Perhaps then we could request to add a "force" routine to the public API of Reactive that ensures all actions are performed.

**Comment by tshort** [comment]
I may try to replace Reactive in Sims. See the following:

https://github.com/tshort/ReactiveBasics.jl

Also, I think the Events are now working, so closing...
