### ISSUE TITLE
Support the use of units in constants, unknown declarations, and equations

### ISSUE THREAD

**Issue by iraikov** [tshort/Sims.jl#9]
It would be convenient to be able to specify units in Sims model declarations, e.g.:

```
using Sims
using SIUnits
using SIUnits.ShortUnits

gL     = 0.2 * mS
vL     = -70.0 * mV
Isyn   = 20.0 * nA
C      = 1.0 * uF

function LeakyIaF()

V = Voltage (-35.0 * mV, "V")
{
   der(V) - (( ((- gL) * (V - vL)) + Isyn) / C)
}

end
```

For this, the various mexpr constructors need to understand SIUnits quantities, and the various Unknown constructors such as Voltage, etc. would need to understand SIUnits and check that they are compatible.

**Comment by tshort** [comment]
I like the idea. We need to be careful not to embed this too deeply. I'd also like to be able to use types without specifying units (the type would have default units). In Modelica, units get in the way too much.

In your example, I'd rather just type:
```julia
V = Voltage(-35.0mV)
V2 = Voltage(2.5)   # defaults to V
```

Maybe the definition of Voltage could just be:
```julia
typealias Voltage Unknown{Volt}   # Volt is an SIUnit
```
`Unknown{T}(val)` could perform unit conversions immediately. I'm not sure we should go deeper than this. For example, if the user wants to add Voltage and a Length, I don't know if it is a good idea to error on that.

**Comment by iraikov** [comment]
I also have encountered several modeling languages where unit declarations
can get in the way too much, so I agree this would take some
experimentation.

In your first example, it seems that you would allow the mixing mV and V in
the same model, but this is a major source of errors in my experience. I
like the second example (typealias) a bit more: it enforces that Voltage
Unknowns will always have a unit of Volt.
So if the user wishes to to have different voltage quantities with
different units then they would have to create several typealiases for each
voltage quantity. On a first impression this seems to be the more
error-free approach.

**Comment by tshort** [comment]
In my first example, I intended that both would have the same units. The variable `V` would be converted to -0.035V internally.

**Comment by tshort** [comment]
I'll go through the standard library and convert to one of these. Any preference?

**Comment by iraikov** [comment]
Perhaps we should start with using SIUnits for the typealiases in types.jl.
Automatic conversion of units sounds nice, but it might get pretty
complicated. I might create a set of "biophysical units" for the neural
models that use mV, ms, and so on by default.

**Comment by tshort** [comment]
I don't think we can use `Unknown{Volt}` because `Volt` is not a type, it's an immutable. That means that units will need to be added as a field to Unknowns.

Surprisingly, the following works right now. 1000.0mV is equivalent to 1.0.

```julia
using SIUnits, Sims
using SIUnits.ShortUnits
function Vanderpol()
    y = Unknown(1000.0mV, "y")   # The 1.0 is the initial value. "y" is for plotting.
    x = Unknown(0.0, "x")        # The initial value is zero if not given.
    # The following gives the return value which is a list of equations.
    # Expressions with Unknowns are kept as expressions. Expressions of
    # regular variables are evaluated immediately (like normal).
    @equations begin
     # The -1.0 in der(x, -1.0) is the initial value for the derivative 
     der(x, -1.0) - ((1 - y^2) * x - y) # == 0 is assumed
     der(y) - x
    end
end

v = Vanderpol()       # returns the hierarchical model
v_f = elaborate(v)    # returns the flattened model
v_s = create_sim(v_f) # returns a "Sim" ready for simulatio

tf = 50.0
dt = 0.025

@time v_yout = sunsim(v_s, tf, int(tf/dt))
```
